### ISSUE TITLE
KeyError: 'logger' when running `Trachoma_Simulation`

### ISSUE THREAD

**Issue by sempwn** [NTD-Modelling-Consortium/ntd-model-trachoma#20]
https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma/blob/8870bf8341fc5fb0f3afa8decb97d0b23d2d4bd8/trachoma/trachoma_simulations.py#L22

I'm not sure how the line above should work given `kwargs` may not necessarily have "logger" in its keys. I'm not sure where else this method is applied but would expect it to check 

```python 
"logger" in kwargs.keys()
``` 

first before checking if `None`

A minimal example of the where this errors is

```python
import Trachoma 
BetFilePath = 'files/InputBet_scen1.csv'  
MDAFilePath = 'files/InputMDA_scen1.csv' 
PrevFilePath = 'files/OutputPrev_scen1.csv'

result = trachoma.Trachoma_Simulation(BetFilePath=BetFilePath,
                    MDAFilePath=MDAFilePath,
                    PrevFilePath=PrevFilePath,
                    SaveOutput=False,
                    OutSimFilePath=None,
                    InSimFilePath=None)
```

Entirely possible I'm missing something, but would expect that if all files stated in parameters exist then should run without error.

**Comment by igorclark** [comment]
Hi Mike, thanks for this! Could be a non-native python programmer causing this problem - the function definition `Trachoma_Simulation` on [line 214 of trachoma/trachoma_simulations.py](https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma/blob/master/trachoma/trachoma_simulations.py#L214) has a default keyword arg `logger`:

```python
@timer
def Trachoma_Simulation(
    BetFilePath, MDAFilePath, PrevFilePath, InfectFilePath,
    SaveOutput=False, OutSimFilePath=None, InSimFilePath=None,
    rho=0.3, MDA_Cov=0.8, numReps=0,
    useCloudStorage=False, download_blob_to_file=None, logger=None
):
```

The intention here was that as the model was being run by a Flask API endpoint, it could thus have `app.logger` passed in, but default to just printing to stdout if called from elsewhere. In the API it's called like this:

```python
            Trachoma_Simulation(
                BetFilePath=bet_file_gcs_path,
                MDAFilePath=mda_file_gcs_path,
                PrevFilePath=output_prevalence_gcs_path,
                InfectFilePath=infect_file_gcs_path,
                InSimFilePath=in_sim_file_path,
                SaveOutput=False,
                OutSimFilePath=None,
                MDA_Cov=MDA_Cov,
                numReps = numReps,
                useCloudStorage=True,
                logger = app.logger,
                download_blob_to_file = gcs.download_blob_to_file,
            )
```
If the function call in your minimal example crashes then it sounds like the default arg isn't working as planned, or this is not the right way to use it, and if so we should definitely add in the args checker in your PR. Seems like there's documentation which has been missed in rushes to hit deadlines too.

However this is from a while ago and there have been a bunch of changes to the model since then; in our cloud runner for the Trachoma model, we don't call that function directly, we have an entry point which calls `def run_single_simulation` from `trachoma/trachoma_simulations.py` which in turn calls `def sim_Ind_MDA_Include_Survey`, so we haven't seen this crash. Great to have it checked and tidied, thanks!

**Comment by sempwn** [comment]
Ah thanks for clarifying. Still getting familiar with the code base so not sure which are the main entry points to the model. PR fixed issue for me, just wasn't sure if would have any unexpected side effects with the fix but sounds like that isn't the case so happy to close. 

Would be useful to have a deprecation flag with this method then if no longer in use. I can create an issue as a suggested feature.
